### ISSUE TITLE
unzip: cannot find or open

### ISSUE THREAD

**Issue by mohammedalsayegh** [AriZuu/cmsis-ports#1]
Hi,

I tried to test makefile in STM32F4xx directory with new last released of STM32F4 DSP and standard peripherals library V1.8. After modifying the version of the released, I have the fallowing message:

`mkdir -p inc
mkdir -p src
mkdir -p tmp
(cd tmp; unzip -q -aa ../../../distfiles/stm32f4_dsp_stdperiph_lib.zip)
unzip:  cannot find or open ../../../distfiles/stm32f4_dsp_stdperiph_lib.zip, ../../../distfiles/stm32f4_dsp_stdperiph_lib.zip.zip or ../../../distfiles/stm32f4_dsp_stdperiph_lib.zip.ZIP.
Makefile:37: recipe for target 'inc/system_stm32f4xx.h' failed
make: *** [inc/system_stm32f4xx.h] Error 9`

Best regards

**Comment by AriZuu** [comment]
Fixed, the name of zip file was changed.
